version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=todoapp.settings 
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: TodoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      