# Generated by Django 5.1.3 on 2025-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='to_be_done_before',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
